### PR TITLE
Linux support

### LINKED ISSUE #15: Linux Support
Currently build is only for windows with no consideration given to Linux. Need someone who can test Linux and revisit electron code to support Linux gotchas.

### PR DESCRIPTION
**Pull request by wetheredge**
I've reorganized the vendor directory into one directory per supported platform. During build, vite copies only the vendor-specific directory. On Linux, it only vendors `blackbox_decode`, since FFmpeg can easily be marked as a dependency and installed automatically through the system package manager.

~~My thought on package formats is to provide `.tar.bz2` and `.deb`, although `.deb` packages do require a maintainer email. In addition, adding Gimbal Ghost to [Flathub](https://flathub.com) ([submission process](https://github.com/flathub/flathub/wiki/App-Submission)) and the [AUR](https://aur.archlinux.org/) ([submission process](https://wiki.archlinux.org/title/Arch_User_Repository#Submitting_packages)) would make it available to a large chunk of Linux users. Of the two, Flathub is easier and probably would reach more end users.~~

**Remaining tasks:**
- [x] Rebuild `blackbox_decode` on Ubuntu LTS for greater compatibility
- [x] Decide on packaging formats & distribution: `AppImage` ~~+ `.tar.bz2`~~
- [x] Finish Linux packaging metadata: icon, category
- [x] Update GitHub workflows

I've probably forgotten something, but I'll keep this updated.

closes #15

### CODE REVIEW

**Comment by joshuadavidson** [comment]
@wetheredge thanks for putting together this task list! If you need an email I can create a generic one off of my domain when/if needed. Only thing that I am hesitant about is veering off the beaten path that `electron-builder` provides with auto-updates and simplified build targets. What makes the default option of an AppImage target provided by `electron-builder` ([docs](https://www.electron.build/auto-update)) not appropriate here?

**Comment by wetheredge** [comment]
Sorry it's taken me so long to get back to this. I suggested additional packaging because the best practice on Linux is to only install things through the system package manager, a la the App Store or Google Play. Auto-update is also a somewhat foreign concept on Linux, as updates are handled through the system package manager. However, I recognize that this is extra work for a platform you might not use.

As a middle ground, how about providing two outputs for Linux:
1. An AppImage closely following the Electron Build defaults
2. `.tar.bz2` for myself and others who prefer to manually package software not available in the system package manager

The AppImage would need a Linux build of `ffmpeg`. I think switching to [`ffmpeg-static`](https://github.com/eugeneware/ffmpeg-static) would make this relatively trivial, and it provides macOS builds if you want to support that in the future.

If this plan sounds good, I can rebase and update this PR in the next few days.

**Comment by joshuadavidson** [comment]
No worries at all man. As far as I'm concerned this Linux support is totally your thing. I just wanted to make sure that whatever was developed could be easily maintained by you or others. I think your middle ground approach sounds good. I'm fine switching to `ffmpeg-static` and disabling auto-update for Linux apps to facilitate this. Let me know if I can be of any further assistance! 😄

**Comment by wetheredge** [comment]
Should be about ready for review. I've dropped the `tar.bz2` Linux build, since there is no way to tell electron builder to include `ffmpeg` in the AppImage, but not in the `tar.bz2`. It would require having a second config file, which, at best, would be a script to generate the second config from the one in the `package.json`:

```javascript
export default async function({ packageMetadata }) {
    const { build: config } = await packageMetadata.value;
  
    config.linux.target[0].target = 'tar.bz2';
    config.extraResources.find(({ to }) => to === 'vendor').filter = '!**/ffmpeg/*';

    return config;
}
```

This would complicate the CI, since building would have to happen in two steps (NSIS + AppImage, then `tar.bz2`). IMO, this probably isn't worth the additional complexity in code, maintenance, and CI. (And I've got an idea for how this could be ported to the web, once I finish something I've been working on, which would ofc provide another option for Linux usage).

I also dropped the idea of using `ffmpeg-static` and just vendored the official Linux x64 build directly, as it only allows downloading the binary for one platform at a time, meaning the targets have to be built sequentially: [docs](https://github.com/eugeneware/ffmpeg-static#electron--other-cross-platform-packaging-tools).

---

I changed the icon used by the Windows build to the PNG extracted from the ICO file. NSIS should support either, but Linux needs a PNG. I don't have a Windows dev environment, so I'd appreciate if you could verify that the NSIS build still works. If you don't have time, I can see if I can get something set up to test myself.

---

I'm not sure how to update the GitHub workflows, as I only have experience with GitLab CI. I think the pull request workflow can just be changed to run on both `windows-2022` and `ubuntu-latest`, but the release will be more complex. Electron builder does provide docker images ([docs](https://www.electron.build/multi-platform-build#docker)) that would allow building both targets at once. It would need to use `electronuserland/builder:wine`, but I'm not sure how to integrate that into the GitHub workflow. It looks like GitHub does allow running jobs in containers: [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer).

---

A final thing I noticed while working on this is that the current appId doesn't fit the recommendation for app IDs, at least [from Flatpak](https://docs.flatpak.org/en/latest/conventions.html#application-ids). I think the compliant ID would be `io.github.gimbal_ghost.GimbalGhost`. Maybe it's too late to change it after 1.0, and maybe it's not too important since it's not going to be published on FlatHub.

**Comment by joshuadavidson** [comment]
Awesome! I've give it a review and build for windows and make sure everything works there. I'll try to have this done this weekend. I'll also take a stab at the GitHub action for building--this might take some more time.

I'm totally on board for moving this to web. I wanted to do it initially as ffmpeg has a Wasm module but I would also need a Wasm module for the blackbox decoder.

**Review by joshuadavidson — CHANGES_REQUESTED** [review]
Everything looks good from a code perspective here. Can you add some documentation to the `RELEASE-HEADER.md` file for users to know how to install for Linux? This file is automatically appended to the top of each release. I'll follow up shortly with a commit for some small tweaks for the windows build.

**Comment by joshuadavidson** [comment]
Made a few small tweaks to get windows building again. Electron didn't like the `png` for some reason. I'll be looking at the GitHub action to build for Linux now. Can you let me know the build artifacts for Linux and which ones should be included in the release?

**Comment by wetheredge** [comment]
Linux just needs `GimbalGhost.AppImage` and `latest-linux.yml`.

Some of the first commits are a bit messy, I can clean those up if you'd like.

**Comment by joshuadavidson** [comment]
No need to clean up commits. I'll squash when I finish up the GitHub workflow testing.

**Comment by wetheredge** [comment]
Sounds good. I've also been messing with the workflows some on the linux-ci branch in my repo, but if you've got it working I can drop it.

**Comment by joshuadavidson** [comment]
Yeah, I've got the combined build working within container just need to test it here. GitHub doesn't have a clean way of testing workflows 😞

**Comment by wetheredge** [comment]
There is https://github.com/nektos/act, but it runs in Docker and the images aren't small

**Comment by joshuadavidson** [comment]
Yeah saw that--I concur. I'll just test here with a bunch of commits if needed 😄

**Review by joshuadavidson — APPROVED** [review]
Thanks for all the help here. I will merge into main and make a release candidate version which we can use to test the release pipeline as well as the build artifacts. Look for it shortly.

**Comment by wetheredge** [comment]
FYI, I found that passing `--publish never` to `electron-builder` allowed it to run successfully without needing the GITHUB_TOKEN

**Comment by joshuadavidson** [comment]
Release pipeline failed with a typo and a bug in the changelog versioning. I'll fix it up and let you know when the release candidate is up.

**Comment by joshuadavidson** [comment]
Ok prerelease is up [here](https://github.com/gimbal-ghost/gimbal-ghost/releases/tag/v1.2.0-rc.0). Go ahead and give the assets a try and let me know how it goes. If all is well I'll push v1.2.0!

**Comment by wetheredge** [comment]
Sorry waiting on results from a second tester. Should be in the next couple hours or so. It did work in my test.

**Comment by wetheredge** [comment]
No problems on either test machine. Thanks for supporting this!

Once I've got https://github.com/wetheredge/blackbox production ready with a WASM/JavaScript interface around it, I'll open a PR to start working on the web port. It'll probably be a while.

**Comment by joshuadavidson** [comment]
Awesome! v1.2.0 is headed out the door. Thanks for your support as well 👍. Looking forward to WASM blackbox support for a web version.

**Pull request merged**
